### ISSUE TITLE
Attribute Editor Template

### ISSUE THREAD

**Issue by alanjfs** [timmwagener/tw_cloth_solver#1]
Hello Timm,

This was a while ago so it might not be at the top of your memory, but when you were working on that lovely AE template of yours, with the nice header image, did you - as I currently am - resort to restarting Maya each time you wanted to update it? I'm searching for a command or method to avoid doing that as it's a real bummer! :D

**Comment by timmwagener** [comment]
Hi Alan,

I blurrily recall that working on the AETemplate felt very uncomfortable, inconvenient and a little outdated. Having to restart the application each time for updates may have contributed to that, _(next to being forced to use MEL at the time)_. There is an ominous [update procedure defined](https://github.com/timmwagener/tw_cloth_solver/blob/master/ae_template/AEverletClothSolverTemplate.mel#L31) which may be a callback to register for updates!? If that's the official API for it, i failed to use it properly, but i'm not sure about that. I believe back then (~2014ish) it wasn't possible to write these templates via Python, maybe by now there's a Python API for it?

**Comment by alanjfs** [comment]
Thanks Timm, I missed the notification on this one but this helps!

**Comment by alanjfs** [comment]
Never did manage to find a way around this. Still restarting Maya whenever I need to change the template. Such a pain. xD
